site_name: Achievement System
site_description: Documentation of an Achievement System.
copyright: openSource
nav:
  - 'index.md'
  - 'about.md'
theme:
  name: material
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
